SCAScreening/SCA_ScreeningSite/Controllers/SCAController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KleinTech.Web.MVC5.Controllers
{
    public class SCAController : Controller
    {
        //
        // GET: /SCA/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Step1()
        {
            return View();
        }

        public ActionResult Step2()
        {
            return View();
        }
	}
}

SCAScreening/SCA_ScreeningSite/Views/SCA/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SCA Screening Steps</h2>

@Html.ActionLink(@"Step 1. Call the SCA servers API and get the trunk size.", "Step1", "SCA") 
<br />
@Html.ActionLink(@"Step 2. Call Reid's Local WebAPI to get the trunksize.", "Step2", "SCA") 
<br />
<br />
The 2 routes to get the JSON TreasureTrunk object are:
<br />
<br />

http://67.184.231.185/WebAPI/api/SCA/ForStep2/ {number of pirates} exp. http://67.184.231.185/WebAPI/api/SCA/ForStep2/3
<br />
or
<br />
http://67.184.231.185/WebAPI/api/TreasureTrunks/{number of Pirates} exp. http://67.184.231.185/WebAPI/api/TreasureTrunks/4

SCAScreening/SCA_ScreeningSite/Views/SCA/Step1.cshtml
@{
    ViewBag.Title = "Step1";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style type="text/css">
    .modal {
        position: fixed;
        top: 0;
        left: 0;
        background-color: black;
        z-index: 99;
        opacity: 0.8;
        filter: alpha(opacity=80);
        -moz-opacity: 0.8;
        min-height: 100%;
        width: 100%;
    }

    .loading {
        font-family: Arial;
        font-size: 10pt;
        border: 5px solid #67CFF5;
        width: 200px;
        height: 100px;
        display: none;
        position: fixed;
        background-color: White;
        z-index: 999;
    }
</style>



<script type="text/javascript">
    function getAnswerFromSCA() {
        jQuery.support.cors = true;
        var numOfPirates = $('#txtNoPirates').val();

        if (numOfPirates == '')
        {
            alert("Please enter the number of pirates, mate.");
            $('#txtNoPirates').focus();
            return;
        }

        $("#divResult").html("Contacting SCA pirates for an answer, Mate. Please Wait...");

        $.ajax({
            url: 'http://pirate.azurewebsites.net/api/Pirate/' + numOfPirates,
            type: 'GET',
            dataType: 'text',
            success: function (data) {
                ShowResult(data);
            },
            error: function (x, y, z) {
                alert(x + '\n' + y + '\n' + z);
            }
        });
    }

    function ShowResult(shareOfGold)
    {
        if (shareOfGold != null)
        {
            $("#divResult").html("SCA says: <b>" + parseInt(shareOfGold) + "</b> is the smallest amount of gold pieces in the chest, Mate!");

        }
        else
        {
            $("#divResult").html("<b>No Response from SCA Mate, sorry. </b>");
        }

    }


</script>



    <h2 style="font-variant:small-caps;"><u>Step 1</u></h2>
    <h4>Call the SCA API to get the smallest number of coins that could be in the trunk, based on a given number of pirates, that divide the share as stated in step1's description.</h4>
    <br />

    How many pirates will be plundering, Mate?
    <br />
    <input id="txtNoPirates" type="text" />
    <button id="btnGetEstimate" onclick="getAnswerFromSCA();">Ok</button>

    <br />
    <br />

    <div id="divResult">

    </div>

    <div id="divResult">

    </div>

SCAScreening/SCA_ScreeningSite/Views/SCA/Step2.cshtml
@{
    ViewBag.Title = "Step2";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style type="text/css">
    .modal {
        position: fixed;
        top: 0;
        left: 0;
        background-color: black;
        z-index: 99;
        opacity: 0.8;
        filter: alpha(opacity=80);
        -moz-opacity: 0.8;
        min-height: 100%;
        width: 100%;
    }

    .loading {
        font-family: Arial;
        font-size: 10pt;
        border: 5px solid #67CFF5;
        width: 200px;
        height: 100px;
        display: none;
        position: fixed;
        background-color: White;
        z-index: 999;
    }
</style>



<script type="text/javascript">

    function getTrunkObject() {
        var numOfPirates = $('#txtNoPirates').val();

        jQuery.support.cors = true;

        if (numOfPirates == '') {
            alert("Please enter the number of pirates that will be dividing this trunk, mate.");
            $('#txtNoPirates').focus();
            return;
        }

        $("#divResult").html("Contacting Reid's Local WebAPI for an answer, Mate. Please Wait...");

        $.getJSON('http://67.184.231.185/WebAPI/api/SCA/ForStep2/' + numOfPirates)
              .done(function (data) {
                  ShowResult(data);
              })
              .fail(function (x, y, z) {
                  alert(x + '\n' + y + '\n' + z);
              });

    }

    function ShowResult(treasureTrunk) {
      
        if (treasureTrunk != null) {
            $("#divResult").html("Reid's API says: <b>" + treasureTrunk.TotalGoldCoins + "</b> is the smallest amount of gold pieces in the chest, Mate!");

        }
        else {
            $("#divResult").html("<b>No Response from Reids WebAPI Dev Server Mate, apologies. Try again later. Thanks! </b>");
        }

    }


</script>



<h2 style="font-variant:small-caps;"><u>Step 2</u></h2>
<h4>Call Reid's Local WebAPI and based on a given number of pirates and the way the do their sharing (as stated in step1's description), return the smallest possible trunk size.</h4>
<br />
    How many pirates will be plundering this trunk, Mate?
<br />
<input id="txtNoPirates" type="text" />
<button id="btnGetEstimate" onclick="getTrunkObject();">Ok</button>

<br />
<br />

<div id="divResult">

</div>

<div id="divResult">

</div>